package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
)

func generate(cfg generatorConfig) error {
	plans, err := planPackages(cfg)
	if err != nil {
		return err
	}
	for _, plan := range plans {
		content, err := renderPackageLogger(plan)
		if err != nil {
			return err
		}
		if err := writeGeneratedFile(plan.OutputPath, content, cfg); err != nil {
			return err
		}
	}

	if cfg.AreasOut != "" {
		content, err := renderAreasRegistry(cfg.AreasOut, plans)
		if err != nil {
			return err
		}
		if err := writeGeneratedFile(cfg.AreasOut, content, cfg); err != nil {
			return err
		}
	}
	return nil
}

func renderPackageLogger(plan packagePlan) ([]byte, error) {
	var buf bytes.Buffer
	_, _ = fmt.Fprintf(&buf, "// Code generated by logcopter-gen; DO NOT EDIT.\n\n")
	_, _ = fmt.Fprintf(&buf, "package %s\n\n", plan.PackageName)
	_, _ = fmt.Fprintf(&buf, "import logcopter %q\n\n", plan.LogcopterImport)
	_, _ = fmt.Fprintf(&buf, "var %s = logcopter.Package(%q)\n", plan.VarName, plan.Area)
	return format.Source(buf.Bytes())
}

func renderAreasRegistry(path string, plans []packagePlan) ([]byte, error) {
	areas := make([]string, 0, len(plans))
	for _, plan := range plans {
		areas = append(areas, plan.Area)
	}
	sort.Strings(areas)

	pkgName := filepath.Base(filepath.Dir(path))
	if pkgName == "." || pkgName == string(filepath.Separator) || pkgName == "" {
		pkgName = "logareas"
	}

	var buf bytes.Buffer
	_, _ = fmt.Fprintf(&buf, "// Code generated by logcopter-gen; DO NOT EDIT.\n\n")
	_, _ = fmt.Fprintf(&buf, "package %s\n\n", pkgName)
	_, _ = fmt.Fprintf(&buf, "var All = []string{\n")
	for _, area := range areas {
		_, _ = fmt.Fprintf(&buf, "\t%q,\n", area)
	}
	_, _ = fmt.Fprintf(&buf, "}\n")
	return format.Source(buf.Bytes())
}

func writeGeneratedFile(path string, content []byte, cfg generatorConfig) error {
	if cfg.DryRun {
		fmt.Printf("DRY write %s\n", path)
		return nil
	}

	old, err := os.ReadFile(path)
	if err == nil && bytes.Equal(old, content) {
		return nil
	}
	if cfg.Check {
		return fmt.Errorf("generated file is not current: %s", path)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, content, 0o644)
}
