package main

import (
	"strings"
	"testing"
)

func TestRenderPackageLogger(t *testing.T) {
	content, err := renderPackageLogger(packagePlan{
		PackageName:     "render",
		LogcopterImport: "github.com/go-go-golems/logcopter/pkg/logcopter",
		VarName:         "log",
		Area:            "app.view.render",
	})
	if err != nil {
		t.Fatalf("renderPackageLogger returned error: %v", err)
	}
	got := string(content)
	for _, want := range []string{
		"// Code generated by logcopter-gen; DO NOT EDIT.",
		"package render",
		"import logcopter \"github.com/go-go-golems/logcopter/pkg/logcopter\"",
		"var log = logcopter.Package(\"app.view.render\")",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("generated content missing %q:\n%s", want, got)
		}
	}
}
